### ISSUE TITLE
vscode-jsonrpc not installed properly as a sqlls dependency

### ISSUE THREAD

**Issue by pbdeuchler** [williamboman/mason.nvim#1281]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Mason is having trouble installing `sqlls` due to a missing npm dependency, `vscode-jsonrpc`

Uninstalling/re-installing doesn't seem to work.

Potentially related: https://github.com/microsoft/vscode-eslint/issues/452

### Expected behavior

Mason to install the proper dependencies

### Affected packages

sqlls, vscode-jsonrpc

### Installation log

```Text
[INFO  Mon May  1 21:25:37 2023] ...ck/lazy/opt/mason.nvim/lua/mason-core/installer/init.lua:193: Installation succeeded for Package(name=sqlls)
```

However, in LSP logs

```
[ERROR][2023-05-01 21:28:33] .../vim/lsp/rpc.lua:734	"rpc"	"sql-language-server"	"stderr"	"internal/modules/cjs/loader.js:934\n  throw err;\n  ^\n\nError: Cannot find module 'vscode-jsonrpc/lib/node/main'\nRequire stack:\n- /Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/dist/src/createConnection.js\n- /Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/dist/src/createServer.js\n- /Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/dist/bin/cli.js\n- /Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/npm_bin/cli.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:27)\n    at Module.require (internal/modules/cjs/loader.js:1003:19)\n    at require (internal/modules/cjs/helpers.js:107:18)\n    at Object.<anonymous> (/Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/dist/src/createConnection.js:7:16)\n    at Module._compile (internal/modules/cjs/loader.js:1114:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)\n    at Module.load (internal/modules/cjs/loader.js:979:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:819:12)\n    at Module.require (internal/modules/cjs/loader.js:1003:19) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/dist/src/createConnection.js',\n    '/Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/dist/src/createServer.js',\n    '/Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/dist/bin/cli.js',\n    '/Users/pdeuchler/.local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server/npm_bin/cli.js'\n  ]\n}\n"
```
```


### Neovim version (>= 0.7)

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

OSX 13.3.1

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `require("mason-registry.index")` is installed.
- OK Registry `github.com/mason-org/mason-registry version: 2023-05-02-jagged-secret` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.3 built on darwin22.1.0.`
- OK curl: `curl 7.87.0 (x86_64-apple-darwin22.0) libcurl/7.87.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0`
- OK gzip: `Apple gzip 403.100.6`
- OK tar: `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
- WARNING pwsh: not available
  - ADVICE:
    - spawn: pwsh failed with exit code - and signal -. pwsh is not executable
- OK bash: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- OK Go: `go version go1.20.3 darwin/arm64`
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- OK Ruby: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin22]`
- OK node: `v14.21.3`
- OK RubyGem: `3.2.33`
- OK npm: `6.14.18`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK java: `openjdk version "17.0.3" 2022-04-19`
- OK javac: `javac 17.0.3`
- OK JAVA_HOME: `openjdk version "17.0.3" 2022-04-19`
- OK luarocks: `/opt/homebrew/bin/luarocks 3.9.2`
- OK python3: `Python 3.9.15`
- OK cargo: `cargo 1.64.0 (387270bc7 2022-09-16)`
- OK pip3: `pip 22.0.4 from /Users/pdeuchler/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pip (python 3.9)`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Mon May  1 22:42:58 2023.
```

**Comment by dioklecijan** [comment]
I can confirm described behaviour.

sql-language-server in [createConnection.ts](https://github.com/joe-re/sql-language-server/blob/9ef1cb11dcd0cd6ac8c486f45a0db2dbc29c2a89/packages/server/src/createConnection.ts) imports from `vscode-jsonrpc`, but [package.json](https://github.com/joe-re/sql-language-server/blob/release/packages/server/package.json) doesn't list`vscode-jsonrpc` as a dependency.

Quick fix:

1. Run `npm i vscode-jsonrpc` from `~/local/share/nvim/mason/packages/sqlls/node_modules/sql-language-server`. 
2. Try `node npm_bin/cli --help`. You should see no errors in output.
3. Open sql file in neovim and run `:LspInfo`. `sqlls` should be listed in "Configured server list".

**Comment by williamboman** [comment]
There seems to be something going on with dependency resolution (sqlls imports `vscode-jsonrpc` but hasn't explicitly stated it in their dependencies so instead relies on it transitively). Using a later version of npm doesn't seem to suffer the same issue, for some reason, so upgrading your npm version is also a solution. Mason currently relies on the Node & npm versions currently available in PATH when starting Neovim, so if you need to use a specific version of npm globally you can leverage npx to temporarily launch a Neovim instance with a specific npm version:

```sh
$ npx -p npm@latest -- nvim --headless -c 'MasonInstall sqlls' -c qa
```

 Anyways, this is an issue that should be filed with the maintainers of sqlls (I might open a PR myself with a suggestion).

**Comment by pbdeuchler** [comment]
Awesome, thank you!
