### ISSUE TITLE
Ansible-language-server how to use?

### ISSUE THREAD

**Issue by unphased** [williamboman/mason.nvim#1420]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Ansible-language-server (ansiblels) installs fine via Mason and gets installed seemingly properly. 

It's never enabled but I can try to enable it myself using `:LspStart ansiblels`, but this immediately leads to the error 

```
LSP[ansiblels]: Error SERVER_REQUEST_HANDLER_ERROR: "...are/nvim/lazy/plenary.nvim/lua/plenary/window/border.lua:219: 'replacement string' item contains newlines"
```

and in the LspLog:

```
[WARN][2023-07-19 23:33:57] ...lsp/handlers.lua:134	"The language server ansiblels triggers a registerCapability handler for workspace/didChangeConfiguration despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-07-19 23:33:57] ...lsp/handlers.lua:134	"The language server ansiblels triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2023-07-19 23:33:57] .../lua/vim/lsp.lua:1190	"LSP[ansiblels]"	"on_error"	{  code = "SERVER_REQUEST_HANDLER_ERROR",  err = "...are/nvim/lazy/plenary.nvim/lua/plenary/window/border.lua:219: 'replacement string' item contains newlines"}
[ERROR][2023-07-19 23:33:57] .../vim/lsp/rpc.lua:677	"rpc"	"/Users/slu/.local/share/nvim/mason/bin/ansible-language-server"	"stderr"	"/Users/slu/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:477\n                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));\n                                               ^\n\nResponseError: ...are/nvim/lazy/plenary.nvim/lua/plenary/window/border.lua:219: 'replacement string' item contains newlines\n    at handleResponse (/Users/slu/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)\n    at processMessageQueue (/Users/slu/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)\n    at Immediate.<anonymous> (/Users/slu/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)\n    at process.processImmediate (node:internal/timers:478:21) {\n  code: -32603,\n  data: undefined\n}\n\nNode.js v20.4.0\n"
```

NOTE: I tried on my nvim setup in Ubuntu 20.04 and it works no problem. Problem is with macOS apple sillicon. 

### Expected behavior

not crash

### Steps to reproduce

1. install ansible-language-server from mason
2. try to use it

### Affected packages

ansible-language-server

### Neovim version (>= 0.7)

NVIM v0.10.0-dev-1936+g91aeaeef6-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

Also tested

NVIM v0.10.0-dev-2050+g86ce3878d-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

macos

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.6.0
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-07-20-ruddy-ling` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.3 built on darwin21.6.0.`
- OK curl: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
- OK gzip: `Apple gzip 353.100.22`
- OK tar: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
- OK bash: `GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- OK Ruby: `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin21]`
- OK node: `v20.4.0`
- OK cargo: `cargo 1.64.0 (387270bc7 2022-09-16)`
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code 1 and signal 0. The operation couldn’t be completed. Unable to locate a Java Runtime.
      Please visit http://www.java.com for information on installing Java.
      
      
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code 1 and signal 0. The operation couldn’t be completed. Unable to locate a Java Runtime.
      Please visit http://www.java.com for information on installing Java.
      
      
- OK python: `Python 3.11.4`
- OK luarocks: `/opt/homebrew/bin/luarocks 3.9.2`
- OK RubyGem: `3.0.3.1`
- OK npm: `9.7.2`
- OK pip: `pip 23.0.1 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 2. Remaining: 58. Limit: 60. Reset: Thu Jul 20 01:09:04 2023.
  Install and authenticate via gh-cli to increase rate limit.
```

**Comment by williamboman** [comment]
Hello! I can't reproduce. The error stacktrace suggests the error is with plenary.nvim. It also seems like something else than nvim-lspconfig is writing to the LSP log, which is weird.

**Comment by unphased** [comment]
Yeah I think i need to try some stuff since it does work right on Linux.
