### ISSUE TITLE
Errors with RuboCop package when extensions are used

### ISSUE THREAD

**Issue by djpowers** [williamboman/mason.nvim#383]
### I believe this to be an issue that should be addressed by maintainers of mason.nvim.

- [X] Yes

### Why do you think this is an issue with mason.nvim?

When installing RuboCop via Mason, there is not a way to automatically pull in the separate packages/gems for any of the various extensions that work with RuboCop: https://docs.rubocop.org/rubocop/extensions.html#cop-extensions

There are over a dozen official and third-party extensions that a project could be using, but right now an error will be thrown if a package is not present, and Mason does not provide a way to install them.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

rubocop

### Problem description

Launching a project using RuboCop installed that uses extensions will result in an error:
```
[null-ls] failed to run generator: ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:232: error in generator output: cannot load such file -- rubocop-rspec
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/feature_loader.rb:39:in `rescue in load'
/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/feature_loader.rb:32:in `load'
/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/feature_loader.rb:21:in `load'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_loader_resolver.rb:12:in `tap'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_loader.rb:46:in `load_file'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_loader.rb:104:in `configuration_from_file'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_store.rb:68:in `for_dir'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/config_store.rb:58:in `for'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/target_finder.rb:190:in `block in process_explicit_path'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/target_finder.rb:189:in `reject'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/target_finder.rb:189:in `process_explicit_path'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/target_finder.rb:40:in `block in find'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/target_finder.rb:36:in `each'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/target_finder.rb:36:in `find'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/runner.rb:81:in `find_target_files'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/runner.rb:42:in `run'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli/command.rb:11:in `run'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli/environment.rb:18:in `run'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli.rb:72:in `run_command'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli.rb:79:in `execute_runners'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/lib/rubocop/cli.rb:48:in `run'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/exe/rubocop:19:in `block in <top (required)>'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
~/.local/share/nvim/mason/packages/rubocop/gems/rubocop-1.35.1/exe/rubocop:19:in `<top (required)>'
~/.local/share/nvim/mason/packages/rubocop/bin/rubocop:23:in `load'
~/.local/share/nvim/mason/packages/rubocop/bin/rubocop:23:in `<main>'
```

### Steps to reproduce

1. Install rubocop via Mason
2. Open a Ruby project that uses a RuboCop extension such as [RuboCop RSpec](https://docs.rubocop.org/rubocop-rspec/index.html)

I was able to "fix" the error by running the plugin locally and editing https://github.com/williamboman/mason.nvim/blob/e912899055911cb65565a39519eb12cfc762a881/lua/mason-registry/rubocop/init.lua#L10 to:
```ruby
install = gem.packages { "rubocop", "rubcocop-rspec", bin = { "rubocop" } },
```

It's probably not practical to automatically install every extension, but I'm hoping that Mason could support some way of adding any extensions in use as needed (whether as totally separate package installs from Mason, or some other means).

### Actual behavior

An error is thrown and the package is not loaded.

### Expected behavior

The package is loaded and usable as a linter/formatter.

### Healthcheck

```Text
Mason: require("Mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: go version go1.19 darwin/arm64
  - OK: **cargo**: cargo 1.63.0 (fd9c4297c 2022-07-01)
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
  - OK: **RubyGem**: `3.1.6`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.18.0`
  - OK: **node**: `v18.8.0`
  - OK: **python3**: Python 3.10.6
  - OK: **pip3**: pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
  - OK: **javac**: javac 17.0.4.1
  - OK: **java**: openjdk version “17.0.4.1" 2022-08-12
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Mon Sep  5 22:13:33 2022.
```

**Comment by williamboman** [comment]
Hello! At first glance this seems similar to a problem that can be generalized to #392. I'll probably fill in details in the issue description, but here's a [short description for now](https://github.com/williamboman/mason.nvim/issues/359#issuecomment-1239651805). I'll go ahead and close this issue for #392, let me know if you disagree

**Comment by djpowers** [comment]
Hi @williamboman, that looks like a great approach! I'll go ahead and subscribe to that issue, thanks for your efforts.

**Comment by djpowers** [comment]
In case others stumble upon this issue, it resurfaced for me when [rubocop-graphql](https://github.com/DmitryTsepelev/rubocop-graphql) was added to a project. I had to modify my previous workaround, I believe because this is a 3rd-party extension in a separate `bin` directory:
https://github.com/williamboman/mason.nvim/blob/e912899055911cb65565a39519eb12cfc762a881/lua/mason-registry/rubocop/init.lua#L10
```ruby
install = gem.packages { "rubocop", "rubocop-rspec", "rubocop-rails", "rubocop-graphql", bin = { "rubocop", "rubocop-graphql" } },
```

You may need to uninstall and reinstall the `rubocop` plugin from Mason.

Note that this syntax is from an older fork. On the latest release any changes would likely be done here: https://github.com/mason-org/mason-registry/blob/main/packages/rubocop/package.yaml

Curious @williamboman if there's a better workaround here for the time being, but otherwise this is serviceable.

**Comment by pointcom** [comment]
Hi @williamboman @djpowers,

Is there a workaround, similar to the one above, that's compatible with the latest version of Mason (using [mason-registry](https://github.com/mason-org/mason-registry/blob/main/packages/rubocop/package.yaml))?

I'm facing the same problem with Rubocop and extensions like rubocop-rspec and rubocop-rails.

From [this comment](https://github.com/williamboman/mason.nvim/issues/359#issuecomment-1239651805), I understand that we could potentially rely on sub-packages in the future. However, I don't believe this is currently an option, correct?

Thanks for your help 🙏

**Comment by djpowers** [comment]
@pointcom I've since migrated to using [Helix](https://helix-editor.com/), partially due to the ease of working with LSP/linters/formatters it provides.

It looks like the sub-packages issue (linked from an earlier reply here) is still open, so I'm assuming that is not yet an option. There was a more recent comment in that thread though that might give you some ideas.
