### ISSUE TITLE
node-debug2-adapter fails to build

### ISSUE THREAD

**Issue by rudotriton** [williamboman/mason.nvim#41]
### Problem description

`npm run build` fails

[nvim-dap](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#javascript) offers `NODE_OPTIONS=--no-experimental-fetch npm run build` as the build command.

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+798acbca1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin triton-mbp.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

node-debug2-adapter

### Actual behavior

```bash
      [13:39:55] Using gulpfile ~/.local/share/nvim/mason/.packages/node-debug2-adapter/gulpfile.js
      [13:39:55] Starting 'build'...
      [13:39:55] Starting 'clean'...
      [13:39:55] Finished 'clean' after 4.69 ms
      [13:39:55] Starting '_build'...
      [13:39:55] Starting 'copy-scripts'...
      [13:39:55] Finished 'copy-scripts' after 20 ms
      [13:39:55] Starting '<anonymous>'...
      [13:39:57] '<anonymous>' errored after 1.87 s
      [13:39:57] Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
          at readWasm (/Users/triton/.local/share/nvim/mason/.packages/node-debug2-adapter/node_modules/gulp-typescript/node_modules/source-map/lib/read-wasm.js:8:13)
          at wasm (/Users/triton/.local/share/nvim/mason/.packages/node-debug2-adapter/node_modules/gulp-typescript/node_modules/source-map/lib/wasm.js:25:16)
          at /Users/triton/.local/share/nvim/mason/.packages/node-debug2-adapter/node_modules/gulp-typescript/node_modules/source-map/lib/source-map-consumer.js:264:14
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      [13:39:57] '_build' errored after 1.89 s
      [13:39:57] 'build' errored after 1.9 s
      spawn: npm failed with exit code 1 and signal 0. 
```

### Expected behavior

with `NODE_OPTIONS=--no-experimental-fetch`:

```bash
[13:29:35] Using gulpfile ~/Projects/Node/vscode-node-debug2/gulpfile.js
[13:29:35] Starting 'build'...
[13:29:35] Starting 'clean'...
[13:29:35] Finished 'clean' after 20 ms
[13:29:35] Starting '_build'...
[13:29:35] Starting 'copy-scripts'...
[13:29:35] Finished 'copy-scripts' after 22 ms
[13:29:35] Starting '<anonymous>'...
[13:29:38] Finished '<anonymous>' after 2.2 s
[13:29:38] Finished '_build' after 2.22 s
[13:29:38] Finished 'build' after 2.25 s
```

### Mason output

```Text
◍ node-debug2-adapter
      Cloning into '.'...
      From https://github.com/microsoft/vscode-node-debug2
       * tag               v1.43.0    -> FETCH_HEAD
      Note: switching to 'FETCH_HEAD'.
      
      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.
      
      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:
      
        git switch -c <new-branch-name>
      
      Or undo this operation with:
      
        git switch -
      
      Turn off this advice by setting config variable advice.detachedHead to false
      
      HEAD is now at 20ee19f 1.43.0
      [13:39:55] Using gulpfile ~/.local/share/nvim/mason/.packages/node-debug2-adapter/gulpfile.js
      [13:39:55] Starting 'build'...
      [13:39:55] Starting 'clean'...
      [13:39:55] Finished 'clean' after 4.69 ms
      [13:39:55] Starting '_build'...
      [13:39:55] Starting 'copy-scripts'...
      [13:39:55] Finished 'copy-scripts' after 20 ms
      [13:39:55] Starting '<anonymous>'...
      [13:39:57] '<anonymous>' errored after 1.87 s
      [13:39:57] Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
          at readWasm (/Users/triton/.local/share/nvim/mason/.packages/node-debug2-adapter/node_modules/gulp-typescript/node_modules/source-map/lib/read-wasm.js:8:13)
          at wasm (/Users/triton/.local/share/nvim/mason/.packages/node-debug2-adapter/node_modules/gulp-typescript/node_modules/source-map/lib/wasm.js:25:16)
          at /Users/triton/.local/share/nvim/mason/.packages/node-debug2-adapter/node_modules/gulp-typescript/node_modules/source-map/lib/source-map-consumer.js:264:14
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      [13:39:57] '_build' errored after 1.89 s
      [13:39:57] 'build' errored after 1.9 s
      spawn: npm failed with exit code 1 and signal 0.
```

### Installation log

```Text
[INFO  Sat Jul  9 13:39:31 2022] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:110: Executing installer for Package(name=node-debug2-adapter)
[ERROR Sat Jul  9 13:39:57 2022] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:146: Installation failed for Package(name=node-debug2-adapter) error=spawn: npm failed with exit code 1 and signal 0. 

```
```


### Healthcheck

```Text
mason-core: require("mason-core.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.62.0 (a748cf5a3 2022-06-08)`
  - OK: **luarocks**: `/usr/local/bin/luarocks 3.9.1`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.9.0`
  - OK: **node**: `v18.1.0`
  - OK: **python3**: `Python 3.9.13`
  - OK: **pip3**: `pip 22.1.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: **python3_host_prog**: `Python 3.9.13`
  - OK: GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Sat Jul  9 14:47:17 2022.
```
```


### Screenshots

_No response_

**Comment by williamboman** [comment]
Should be fixed in #47!
