### ISSUE TITLE
Failed to install vue-language-server@1.0.0

### ISSUE THREAD

**Issue by niuiic** [williamboman/mason.nvim#448]
### I've made an initial investigation into the error myself

- [x] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [x] Yes

### Problem description

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:1.0.0-alpha.0
```
`workspace` is not supported by npm. This problem should be solved by using yarn or pnpm instead.

### Neovim version (>= 0.7)

```
NVIM v0.8.0-dev-1059-g2d6735d8c-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system/version

```
Linux niuiic 5.19.9-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 16 21:19:43 CST 2022 x86_64 12th Gen Intel(R) Core(TM) i7-12700H GenuineIntel GNU/Linux
```

### Affected packages

vue-language-server

### Installation log

```
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.13.2
2 info using node@v18.6.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/usr/lib64/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/niuiic/.local/share/nvim/mason/.packages/vue-language-server/.npmrc Completed in 1ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/home/niuiic/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm install @volar/vue-language-server typescript
23 verbose argv "install" "@volar/vue-language-server" "typescript"
24 timing npm:load:setTitle Completed in 0ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/home/niuiic/.npm/_logs
28 verbose logfile /home/niuiic/.npm/_logs/2022-09-20T14_57_01_822Z-debug-0.log
29 timing npm:load:logFile Completed in 2ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 15ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 0ms
37 timing idealTree:init Completed in 6ms
38 timing idealTree:userRequests Completed in 1ms
39 silly idealTree buildDeps
40 silly fetch manifest @volar/vue-language-server@*
41 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2fvue-language-server 9ms (cache hit)
42 silly fetch manifest typescript@*
43 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/typescript 23ms (cache hit)
44 silly placeDep ROOT @volar/vue-language-server@1.0.0-alpha.0 OK for: @mason/vue-language-server@1.0.0 want: *
45 silly placeDep ROOT typescript@4.8.3 OK for: @mason/vue-language-server@1.0.0 want: *
46 silly fetch manifest @volar/language-core@1.0.0-alpha.0
47 silly fetch manifest @volar/language-server@1.0.0-alpha.0
48 silly fetch manifest @volar/shared@1.0.0-alpha.0
49 silly fetch manifest @volar/vue-language-service@1.0.0-alpha.0
50 silly fetch manifest vscode-languageserver-protocol@^3.17.2
51 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2flanguage-server 10ms (cache hit)
52 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2flanguage-core 11ms (cache hit)
53 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2fvue-language-service 10ms (cache hit)
54 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2fshared 12ms (cache hit)
55 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-languageserver-protocol 13ms (cache hit)
56 timing idealTree:#root Completed in 102ms
57 silly placeDep node_modules/@volar/vue-language-server @volar/language-core@1.0.0-alpha.0 OK for: @volar/vue-language-server@1.0.0-alpha.0 want: 1.0.0-alpha.0
58 silly placeDep node_modules/@volar/vue-language-server @volar/language-server@1.0.0-alpha.0 OK for: @volar/vue-language-server@1.0.0-alpha.0 want: 1.0.0-alpha.0
59 silly placeDep node_modules/@volar/vue-language-server @volar/shared@1.0.0-alpha.0 OK for: @volar/vue-language-server@1.0.0-alpha.0 want: 1.0.0-alpha.0
60 silly placeDep node_modules/@volar/vue-language-server @volar/vue-language-service@1.0.0-alpha.0 OK for: @volar/vue-language-server@1.0.0-alpha.0 want: 1.0.0-alpha.0
61 silly placeDep node_modules/@volar/vue-language-server vscode-languageserver-protocol@3.17.2 OK for: @volar/vue-language-server@1.0.0-alpha.0 want: ^3.17.2
62 silly fetch manifest @volar/code-gen@1.0.0-alpha.0
63 silly fetch manifest @volar/source-map@1.0.0-alpha.0
64 silly fetch manifest @vue/reactivity@^3.2.38
65 silly fetch manifest @volar/language-service@1.0.0-alpha.0
66 silly fetch manifest request-light@^0.5.8
67 silly fetch manifest upath@^2.0.1
68 silly fetch manifest vscode-html-languageservice@^5.0.1
69 silly fetch manifest vscode-languageserver@^8.0.2
70 silly fetch manifest vscode-languageserver-textdocument@^1.0.7
71 silly fetch manifest vscode-uri@^3.0.3
72 silly fetch manifest @johnsoncodehk/html2pug@^1.0.0
73 silly fetch manifest @volar-plugins/css@1.0.0-alpha.0
74 silly fetch manifest @volar-plugins/emmet@1.0.0-alpha.0
75 silly fetch manifest @volar-plugins/html@1.0.0-alpha.0
76 silly fetch manifest @volar-plugins/json@1.0.0-alpha.0
77 silly fetch manifest @volar-plugins/pug@1.0.0-alpha.0
78 silly fetch manifest @volar-plugins/pug-beautify@1.0.0-alpha.0
79 silly fetch manifest @volar-plugins/typescript@1.0.0-alpha.0
80 silly fetch manifest @volar/transforms@1.0.0-alpha.0
81 silly fetch manifest @volar/typescript-language-service@1.0.0-alpha.0
82 silly fetch manifest @volar/vue-language-core@1.0.0-alpha.0
83 silly fetch manifest @vue/compiler-dom@^3.2.38
84 silly fetch manifest @vue/shared@^3.2.38
85 silly fetch manifest vscode-json-languageservice@^5.1.0
86 silly fetch manifest vscode-jsonrpc@8.0.2
87 silly fetch manifest vscode-languageserver-types@3.17.2
88 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2flanguage-service 25ms (cache hit)
89 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/request-light 25ms (cache hit)
90 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/upath 25ms (cache hit)
91 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2fsource-map 27ms (cache hit)
92 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-uri 26ms (cache hit)
93 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-languageserver-textdocument 28ms (cache hit)
94 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@johnsoncodehk%2fhtml2pug 27ms (cache hit)
95 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2fcode-gen 31ms (cache hit)
96 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar-plugins%2femmet 29ms (cache hit)
97 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar-plugins%2fcss 30ms (cache hit)
98 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar-plugins%2ftypescript 29ms (cache hit)
99 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar-plugins%2fhtml 30ms (cache hit)
100 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar-plugins%2fjson 29ms (cache hit)
101 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar-plugins%2fpug-beautify 29ms (cache hit)
102 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2ftypescript-language-service 29ms (cache hit)
103 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar-plugins%2fpug 31ms (cache hit)
104 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@vue%2freactivity 34ms (cache hit)
105 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2fvue-language-core 32ms (cache hit)
106 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-languageserver 36ms (cache hit)
107 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-html-languageservice 39ms (cache hit)
108 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@vue%2fshared 37ms (cache hit)
109 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2ftransforms 40ms (cache hit)
110 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-languageserver-types 40ms (cache hit)
111 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-json-languageservice 42ms (cache hit)
112 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@vue%2fcompiler-dom 45ms (cache hit)
113 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-jsonrpc 45ms (cache hit)
114 timing idealTree:node_modules/@volar/vue-language-server Completed in 60ms
115 timing idealTree:node_modules/typescript Completed in 0ms
116 silly placeDep node_modules/@volar/vue-language-server @volar/code-gen@1.0.0-alpha.0 OK for: @volar/language-core@1.0.0-alpha.0 want: 1.0.0-alpha.0
117 silly placeDep node_modules/@volar/vue-language-server @volar/source-map@1.0.0-alpha.0 OK for: @volar/language-core@1.0.0-alpha.0 want: 1.0.0-alpha.0
118 silly placeDep node_modules/@volar/vue-language-server @vue/reactivity@3.2.39 OK for: @volar/language-core@1.0.0-alpha.0 want: ^3.2.38
119 silly fetch manifest @vue/shared@3.2.39
120 timing idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/language-core Completed in 2ms
121 timing idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/code-gen Completed in 0ms
122 silly placeDep node_modules/@volar/vue-language-server @volar/language-service@1.0.0-alpha.0 OK for: @volar/language-server@1.0.0-alpha.0 want: 1.0.0-alpha.0
123 silly placeDep node_modules/@volar/vue-language-server request-light@0.5.8 OK for: @volar/language-server@1.0.0-alpha.0 want: ^0.5.8
124 silly placeDep node_modules/@volar/vue-language-server upath@2.0.1 OK for: @volar/language-server@1.0.0-alpha.0 want: ^2.0.1
125 silly placeDep node_modules/@volar/vue-language-server vscode-html-languageservice@5.0.2 OK for: @volar/language-server@1.0.0-alpha.0 want: ^5.0.1
126 silly placeDep node_modules/@volar/vue-language-server vscode-languageserver@8.0.2 OK for: @volar/language-server@1.0.0-alpha.0 want: ^8.0.2
127 silly placeDep node_modules/@volar/vue-language-server vscode-languageserver-textdocument@1.0.7 OK for: @volar/language-server@1.0.0-alpha.0 want: ^1.0.7
128 silly placeDep node_modules/@volar/vue-language-server vscode-uri@3.0.6 OK for: @volar/language-server@1.0.0-alpha.0 want: ^3.0.3
129 silly fetch manifest @volar/typescript-faster@1.0.0-alpha.0
130 silly fetch manifest vscode-languageserver-types@^3.17.2
131 silly fetch manifest vscode-nls@^5.2.0
132 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/vscode-nls 3ms (cache hit)
133 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/@volar%2ftypescript-faster 6ms (cache hit)
134 timing idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/language-server Completed in 11ms
135 silly placeDep node_modules/@volar/vue-language-server @volar/transforms@1.0.0-alpha.0 OK for: @volar/language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
136 silly placeDep node_modules/@volar/vue-language-server @volar/typescript-faster@1.0.0-alpha.0 OK for: @volar/language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
137 silly placeDep node_modules/@volar/vue-language-server vscode-json-languageservice@5.1.0 OK for: @volar/language-service@1.0.0-alpha.0 want: ^5.1.0
138 silly fetch manifest semver@^7.3.7
139 silly fetch manifest jsonc-parser@^3.1.0
140 silly fetch manifest vscode-languageserver-types@^3.17.1
141 silly fetch manifest vscode-nls@^5.0.1
142 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/semver 3ms (cache hit)
143 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/jsonc-parser 4ms (cache hit)
144 timing idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/language-service Completed in 6ms
145 timing idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/shared Completed in 0ms
146 timing idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/source-map Completed in 0ms
147 silly placeDep node_modules/@volar/vue-language-server vscode-languageserver-types@3.17.2 OK for: @volar/transforms@1.0.0-alpha.0 want: ^3.17.2
148 timing idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/transforms Completed in 1ms
149 silly placeDep node_modules/@volar/vue-language-server semver@7.3.7 OK for: @volar/typescript-faster@1.0.0-alpha.0 want: ^7.3.7
150 silly fetch manifest lru-cache@^6.0.0
151 http fetch GET 200 http://mirrors.cloud.tencent.com/npm/lru-cache 1ms (cache hit)
152 timing idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/typescript-faster Completed in 4ms
153 silly placeDep node_modules/@volar/vue-language-server @johnsoncodehk/html2pug@1.0.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: ^1.0.0
154 silly placeDep node_modules/@volar/vue-language-server @volar-plugins/css@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
155 silly placeDep node_modules/@volar/vue-language-server @volar-plugins/emmet@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
156 silly placeDep node_modules/@volar/vue-language-server @volar-plugins/html@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
157 silly placeDep node_modules/@volar/vue-language-server @volar-plugins/json@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
158 silly placeDep node_modules/@volar/vue-language-server @volar-plugins/pug@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
159 silly placeDep node_modules/@volar/vue-language-server @volar-plugins/pug-beautify@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
160 silly placeDep node_modules/@volar/vue-language-server @volar-plugins/typescript@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
161 silly placeDep node_modules/@volar/vue-language-server @volar/typescript-language-service@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
162 silly placeDep node_modules/@volar/vue-language-server @volar/vue-language-core@1.0.0-alpha.0 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: 1.0.0-alpha.0
163 silly placeDep node_modules/@volar/vue-language-server @vue/compiler-dom@3.2.39 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: ^3.2.38
164 silly placeDep node_modules/@volar/vue-language-server @vue/shared@3.2.39 OK for: @volar/vue-language-service@1.0.0-alpha.0 want: ^3.2.38
165 silly fetch manifest domelementtype@^2.2.0
166 silly fetch manifest domhandler@^4.3.1
167 silly fetch manifest htmlparser2@^7.2.0
168 silly fetch manifest pug@^3.0.2
169 silly fetch manifest vscode-css-languageservice@^6.1.0
170 silly fetch manifest @vscode/emmet-helper@^2.8.4
171 silly fetch manifest @volar/pug-language-service@1.0.0-alpha.0
172 silly fetch manifest @johnsoncodehk/pug-beautify@^0.2.2
173 timing idealTree Completed in 205ms
174 timing command:install Completed in 209ms
175 verbose stack Error: Unsupported URL Type "workspace:": workspace:1.0.0-alpha.0
175 verbose stack     at unsupportedURLType (/usr/lib64/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:262:15)
175 verbose stack     at fromURL (/usr/lib64/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:322:13)
175 verbose stack     at Function.resolve (/usr/lib64/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:80:12)
175 verbose stack     at /usr/lib64/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1081:38
175 verbose stack     at Array.map (<anonymous>)
175 verbose stack     at visit (/usr/lib64/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1080:56)
175 verbose stack     at visitNode (/usr/lib64/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:58:25)
175 verbose stack     at next (/usr/lib64/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
175 verbose stack     at depth (/usr/lib64/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:83:10)
175 verbose stack     at depth (/usr/lib64/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)
176 verbose cwd /home/niuiic/.local/share/nvim/mason/.packages/vue-language-server
177 verbose Linux 5.19.9-gentoo-x86_64
178 verbose node v18.6.0
179 verbose npm  v8.13.2
180 error code EUNSUPPORTEDPROTOCOL
181 error Unsupported URL Type "workspace:": workspace:1.0.0-alpha.0
182 verbose exit 1
183 timing npm Completed in 249ms
184 verbose unfinished npm timer reify 1663685821862
185 verbose unfinished npm timer reify:loadTrees 1663685821863
186 verbose unfinished npm timer idealTree:buildDeps 1663685821872
187 verbose unfinished npm timer idealTree:node_modules/@volar/vue-language-server/node_modules/@volar/vue-language-service 1663685822060
188 verbose code 1
189 error A complete log of this run can be found in:
189 error     /home/niuiic/.npm/_logs/2022-09-20T14_57_01_822Z-debug-0.log
```

### Healthcheck

```
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.1 linux/amd64`
  - OK: **cargo**: `cargo 1.65.0-nightly (082503982 2022-09-13)`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.13.2`
  - OK: **node**: `v18.6.0`
  - OK: **python3**: `Python 3.10.6`
  - OK: **pip3**: `pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.84.0 (x86_64-pc-linux-gnu) libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 nghttp2/1.47.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **python3_host_prog**: `Python 3.10.6`
  - OK: GitHub API rate limit. Used: 5. Remaining: 55. Limit: 60. Reset: Tue 20 Sep 2022 11:53:39 PM CST.
```

**Comment by williamboman** [comment]
You seem to be trying to install an alpha version which as the name suggests isn't necessarily stable. Try installing the next version `1.0.0-alpha.1`
