### ISSUE TITLE
`spectral-language-server` won't install

### ISSUE THREAD

**Issue by LeviticusNelson** [williamboman/mason.nvim#863]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

1. I am unable to install `spectral-language-server` 
2. I can install/update anything else besides this lsp

### Expected behavior

I expected to install this lsp with no issues

### Affected packages

spectral-language-server

### Mason output

```Text
Cloning into '.'...
        From https://github.com/stoplightio/vscode-spectral
         * tag               v1.1.0     -> FETCH_HEAD
        Note: switching to 'FETCH_HEAD'.
        
        You are in 'detached HEAD' state. You can look around, make experimental
        changes and commit them, and you can discard any commits you make in this
        state without impacting any branches by switching back to a branch.
        
        If you want to create a new branch to retain commits you create, you may
        do so (now or later) by using -c with the switch command. Example:
        
          git switch -c <new-branch-name>
        
        Or undo this operation with:
        
          git switch -
        
        Turn off this advice by setting config variable advice.detachedHead to false
        
        HEAD is now at 2e31397 chore: release v1.1.0
        npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
        npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
        npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
        npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
        npm WARN deprecated vsce@1.103.1: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.
        npm WARN deprecated vscode-test@1.5.0: This package has been renamed to @vscode/test-electron, please update to the new name
        
        added 764 packages, and audited 767 packages in 18s
        
        87 packages are looking for funding
          run `npm fund` for details
        
        9 vulnerabilities (2 moderate, 4 high, 3 critical)
        
        To address issues that do not require attention, run:
          npm audit fix
        
        To address all issues (including breaking changes), run:
          npm audit fix --force
        
        Run `npm audit` for details.
        
        ------------------------------------------------------------
        Target: Package
        ------------------------------------------------------------
        
        ------------------------------------------------------------
        Target: BuildAll
        ------------------------------------------------------------
        
        ------------------------------------------------------------
        Target: Clean
        ------------------------------------------------------------
        
        > yarn --ignore-engines --silent clean
        
        > yarn
        yarn install v1.22.19
        error An unexpected error occurred: "Invalid value type 724:0 in /Users/levi/.local/share/nvim/mason/.packages/spectral-language-server/build/yarn.lock".
        ,,
        info If you think this is a bug, please open a bug report with the information provided in "/Users/levi/.local/share/nvim/mason/.packages/spectral-language-server/build/yarn-error.log".
        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
        node:internal/errors:867
          const err = new Error(message);
                      ^
        
        Error: Command failed: yarn
            at checkExecSyncError (node:child_process:885:11)
            at Object.execSync (node:child_process:957:15)
            at run (/Users/levi/.local/share/nvim/mason/.packages/spectral-language-server/build/make.js:133:18)
            at buildAll (/Users/levi/.local/share/nvim/mason/.packages/spectral-language-server/build/make.js:70:3)
            at target.package (/Users/levi/.local/share/nvim/mason/.packages/spectral-language-server/build/make.js:36:9)
            at global.target.<computed> [as package] (/Users/levi/.local/share/nvim/mason/.packages/spectral-language-server/build/node_modules/shelljs/make.js:36:40)
            at /Users/levi/.local/share/nvim/mason/.packages/spectral-language-server/build/node_modules/shelljs/make.js:48:27
            at Array.forEach (<anonymous>)
            at Timeout._onTimeout (/Users/levi/.local/share/nvim/mason/.packages/spectral-language-server/build/node_modules/shelljs/make.js:46:10) {
          status: 1,
          signal: null,
          output: [ null, null, null ],
          pid: 3668,
          stdout: null,
          stderr: null
        }
        
        Node.js v19.4.0
        spawn: node failed with exit code 1 and signal 0.
```

### Installation log

```Text
[INFO  Sat Jan  7 09:04:24 2023] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=spectral-language-server)
[ERROR Sat Jan  7 09:04:44 2023] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=spectral-language-server) error=spawn: node failed with exit code 1 and signal 0.
```

### Neovim version (>= 0.7)

NVIM v0.9.0-dev-629+gd89290b45-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by levi@nelson.local

### Operating system/version

Darwin nelson.local 22.3.0 Darwin Kernel Version 22.3.0: Sun Dec  4 18:17:21 PST 2022; root:xnu-8792.80.21.0.2~9/RELEASE_ARM64_T6000 arm64

### Healthcheck

```Text
mason.nvim report ~
- OK neovim version >= 0.7.0
- OK **Go**: `go version go1.19.4 darwin/arm64`
- OK **cargo**: `cargo 1.66.0 (d65d197ad 2022-11-15)`
- OK **luarocks**: `/opt/homebrew/bin/luarocks 3.9.1`
- OK **Ruby**: `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]`
- OK **RubyGem**: `3.0.3.1`
- OK **Composer**: `Composer version 2.5.1 2022-12-22 15:33:54`
- OK **PHP**: `PHP 8.2.1 (cli) (built: Jan  5 2023 19:28:02) (NTS)`
- OK **npm**: `9.2.0`
- OK **node**: `v19.4.0`
- OK **python3**: `Python 3.10.9`
- OK **pip3**: `pip 22.3.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)`
- OK **javac**: `javac 18.0.2.1`
- OK **java**: `openjdk version "18.0.2.1" 2022-08-18`
- OK **julia**: `julia version 1.8.3`
- OK **wget**: `GNU Wget 1.21.3 built on darwin22.1.0.`
- OK **curl**: `curl 7.86.0 (x86_64-apple-darwin22.0) libcurl/7.86.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0`
- OK **gzip**: `Apple gzip 400`
- OK **tar**: `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
- WARNING **pwsh**: not available
- OK **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)`
- OK **sh**: `Ok`
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Sat Jan  7 10:09:50 2023.
```

**Comment by RyuhoW** [comment]
I have a same problem too.

**Comment by Rhymond** [comment]
I run commands one by one from:
https://github.com/williamboman/mason.nvim/blob/10ff879fc56160e10437da5c1ca558371ddb6989/lua/mason-registry/index/spectral-language-server/init.lua#L9

And I manage to install server with `yarn install` instead of `npm install`

**Comment by williamboman** [comment]
This should be fixed in the new registry as it ensures yarn@1 is installed (I'll assume it was failing because you have a different yarn version installed).
